### ISSUE TITLE
el.setAttribute is not a function

### ISSUE THREAD

**Issue by hackuun** [dollarshaveclub/scrolldir#43]
Hi. I am trying to use `scrolldir` on specific element, but got an error

```js
scrollDir({ el: 'scrolldirtest' }) or scrollDir({ el: '.scrolldirtest' })
```
```
[Vue warn]: Error in mounted hook: "TypeError: el.setAttribute is not a function"
```
Everything else is working fine.

**Comment by yowainwright** [comment]
I'll work on a CodePen for this issue so that the problem can be debugged easier. 

Thanks for pointing this out! 🙏

**Comment by hackuun** [comment]
@yowainwright here - https://codepen.io/kodej/pen/pdzGRY
Thanks for your support!

**Comment by yowainwright** [comment]
@iamdubx I'm working on this. It will be a bit more time but it should be good.

**Comment by pwfisher** [comment]
`opts.el` should be a DOM node (with a `setAttribute` function), not a string (CSS selector or classname). Try

```
const element = document.getElementsByClassName('scrolldirtest')[0]
scrollDir({ el: element })
```

**Comment by pwfisher** [comment]
https://codepen.io/anon/pen/ZaWBaJ
