### ISSUE TITLE
Quick question. 

### ISSUE THREAD

**Issue by jcklpe** [dollarshaveclub/scrolldir#53]
Please excuse my ignorance. I'm a designer learning to code. I was linked this library and it seems really rad! It's only focused on scroll direction though correct? It can't be used to trigger things on an anchor tag etc coming into view correct?

**Comment by yowainwright** [comment]
@thedonquixotic only the scroll direction! 😬  It is a micro utility meant to do just that 1 thing! 

~Thanks 🙏

**Comment by jcklpe** [comment]
Excellent, that's what I thought. I appreciate the focus!
