### ISSUE TITLE
Browsers Supports

### ISSUE THREAD

**Issue by samuelecalamita** [dollarshaveclub/scrolldir#54]
I have noticed on the major Desktop browsers it worked just fine, but on safari mobile seems to not work. Touch gestures supports will be just fine, i´m looking forward to.

**Comment by yowainwright** [comment]
@samuelecalamita could you provide an example in the form of a codepen or jsbin of your issue?

**Comment by samuelecalamita** [comment]
@yowainwright yes sure
https://codepen.io/samuelecalamita/pen/mpwKpq

**Comment by yowainwright** [comment]
Thanks @samuelecalamita!

- that **could be** a "code editor on device issue". Sorry, I didn't think of that earlier.
- here's an [example to check on mobile in production](https://content.dollarshaveclub.com/lose-weight-without-giving-booze). 
  - if it looks okay there, then the plugin is good and working as expected.
  - if not, thanks for pointing out a bug that I will fix asap!!!

**Comment by samuelecalamita** [comment]
@yowainright what do you mean with “code editor on device issue”? Is a bug that comes with codepen?
The example that you have sent works just fine ✅

**Comment by yowainwright** [comment]
Yeah, on Codepen or JsBin on a device, it can be more work to view stuff in a working format because the contents is in an `<iframe>`. I think it can be done! It is more challenging. 😬

@samuelecalamita, Thanks for your time and help debugging!!! 🙏
