### ISSUE TITLE
features requests

### ISSUE THREAD

**Issue by stratboy** [dollarshaveclub/scrolldir#85]
Hi! thank you for your code. It would be great if this plugin also had the following features:

- top/bottom detection

- possibility to use classes instead of data attributes > so you can chain for ex. up.top. It can be useful on the following use case:

> top: full menu
> down: hamburger
> up (:not(.top)): light menu

Yes it can easily be done manually with little external code, but it would be wanderful if implemented here :) 

- Some simple event to hook to get some scroll data.

**Comment by yowainwright** [comment]
@stratboy I don't understand this issue. 

Please provide a code snippet and examples.

**Comment by stratboy** [comment]
If you do this kind of questions alredy, on the first 2 issues you receive, I guess you won't go too far. I suggest you to try again to understand, it can be really more instructive than asking me. 
Anyway, sorry I already coded another class to give these kind of services (complete rewrite, from another point of view), and implemented everything I needed. So I don't need scrolldir anymore. Thank you anyway.
