### ISSUE TITLE
if scrolling down really slowly, data-scrolldir doesn't chage

### ISSUE THREAD

**Issue by stratboy** [dollarshaveclub/scrolldir#87]
This is quite a bad bug. Use case:

1. scroll down
2. scroll up (at this point data-scrolldir == up)
3. scroll down again, very slowly

data-scrolldir will remain == up, even if I'm scrolling down until a certain point (very often 2-300px later, so very much).

**Comment by yowainwright** [comment]
@stratboy Please provide a code snippet and context into what you're looking at.

**Comment by stratboy** [comment]
@yowainwright maybe consider just testing your own code in any context with the above use case before asking for a context.
