### ISSUE TITLE
scrollDir({ direction: 'up' }) has no effect in 1.5.0

### ISSUE THREAD

**Issue by adesurirey** [dollarshaveclub/scrolldir#94]
Hi, 
I just upgraded from 1.2.18 to 1.5.0 and the `direction` option has no effect anymore. I had to migrate to `dir` option as seen in source code. Should we add it to the doc ?

**Comment by yowainwright** [comment]
@adesurirey, lemme check. Support was not intentionally dropped. Perhaps it has to do with compilation updates.

Thanks for letting me know!

**Comment by yowainwright** [comment]
Ha, @adesurirey, it's `dir`, not `direction`. 

- [example](https://codepen.io/yowainwright/pen/be12ad8167dac6f835421a36ec1d5787)
